# Getting Started  
### Best affordable 3D printer  
Hands down, the best printer value 3D printer you can currently buy is the Creality Ender 3 Pro.  It is an extremely precise, reliable, well-constructed printer build kit and it only costs around [$200 or less](https://www.banggood.com/Creality-3D-Ender-3-DIY-3D-Printer-Kit-220x220x250mm-Printing-Size-With-Power-Resume-Function-or-V-Slot-with-POM-Wheel-or-1_75mm-0_4mm-Nozzle-p-1278399.html?cur_warehouse=CN&rmmds=buy).  
I personally use the pro model of the Ender 3 because I got it on sale for around $100 off, but if it's not on sale the added upgrades aren't really worth the price.  
If you would like to use an SLA printer for smaller, more detailed prints, the [Elogoo Mars](https://www.elegoo.com/products/elegoo-mars-lcd-3d-printer) is by fare the best budget option.
### Getting The Files
There are tons of online resources for free 3D pritnable files (STL files) but the best by far is [Thingiverse](https://www.thingiverse.com/).  You can also design your own files using a variety of 3D modelling software like [Inventor](https://www.autodesk.com/products/inventor/new-features?mktvar002=3502049|SEM|292754951|98632079939|kwd-297639773476&ef_id=Cj0KCQjw9_mDBhCGARIsAN3PaFMqaEdKVLGRwXGNVcLI_UJ5UHGZgKfdOqpnuGndoWTqvWN3f7a3C6AaAoLREALw_wcB:G:s&s_kwcid=AL!11172!3!461433301376!e!!g!!cad%20inventor!292754951!98632079939&mkwid=saua9hJuz|pcrid|461433301376|pkw|cad%20inventor|pmt|e|pdv|c|slid||pgrid|98632079939|ptaid|kwd-297639773476|pid|&utm_medium=cpc&utm_source=google&utm_campaign=GGL_INVENTOR_US_BR_SEM_EXACT&utm_term=cad%20inventor&utm_content=saua9hJuz|pcrid|461433301376|pkw|cad%20inventor|pmt|e|pdv|c|slid||pgrid|98632079939|ptaid|kwd-297639773476|&gclid=Cj0KCQjw9_mDBhCGARIsAN3PaFMqaEdKVLGRwXGNVcLI_UJ5UHGZgKfdOqpnuGndoWTqvWN3f7a3C6AaAoLREALw_wcB), [Solidworks](https://www.solidworks.com/), or even free options like [Blender](https://www.blender.org/).
### Printing the files  
A 3D printer can't take a 3D mesh file and know how to print it.  First, the file must be sliced horizontally into layers using a program called a slicer.  I think [Cura](https://ultimaker.com/software/ultimaker-cura) is the best free option but [slic3r](https://slic3r.org/) is a great open source option.  Once the slicer slices the file into layers, it generates machine code which is a set of instructions telling the printer what to do in the form of a GCODE file.  Now you just need to save the GCODE file to a micro-SD card or USB drive, plug it into your prnter, and hit start!  
[Home](https://github.com/pgkraus/3D-Printing-Basics/edit/main/README.md)  
